controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

home_fallback:
    path: /
    controller: App\Controller\MainController::index
    defaults:
        path: /specialites.vlabs
        permanent: true